# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RCTACPGriffon' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for RCTACPReactNativeAcpGriffon
  react_native_path = "../node_modules/react-native"

  pod "React-Core", :path => "#{react_native_path}/React"
  pod "React-cxxreact", :path => "#{react_native_path}/ReactCommon/cxxreact"
  pod "React-jsi", :path => "#{react_native_path}/ReactCommon/jsi"
  pod "React-jsiexecutor", :path => "#{react_native_path}/ReactCommon/jsiexecutor"
  pod "React-jsinspector", :path => "#{react_native_path}/ReactCommon/jsinspector"


  pod 'DoubleConversion', :podspec => "#{react_native_path}/third-party-podspecs/DoubleConversion.podspec"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "Folly", :podspec => "#{react_native_path}/third-party-podspecs/Folly.podspec"


end
