/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 * 
 */

import React, { Component } from 'react';

// const RNACPCore = require('@adobe/react-native-acpcore'); 
// const ACPCore = RNACPCore.ACPCore;
// import ACPGriffon from '@adobe/react-native-acpgriffon';
import {ACPGriffon} from 'react-native-acpgriffon';
// const RNACPGriffon = require('react-native-acpgriffon'); 
// const ACPGriffon = RNACPGriffon.ACPGriffon;

import { StyleSheet, View, Text, Alert, ImageBackground } from 'react-native';
Alert.alert('<><<>>'+ JSON.stringify(ACPGriffon));

export default class App extends Component {
  state = {
    isRegistered: false,
    version: ""
  };

  componentDidMount() {
    // if(ACPGriffon){
    // ACPGriffon.registerExtension().then((hasRegistered) => {
    //   this.setState(() => ({isRegistered: hasRegistere}));
    // });
    // }
    // ACPCore.start().then((hasStarted) => {
    //   Alert.alert('acp core started');
    //   ACPCore.configureWithAppId("94f571f308d5/e30a9514788b/launch-44fec1a705f1-development");
    // });
  }

  startGriffonSession = () => {
    // if(ACPGriffon){
    //   ACPGriffon.startGriffonSession("grifflab://shtomar-griffon?adb_validation_sessionid=a7cad5ab-d8df-4883-9bd4-42dc5725e228");
    // }
  };

  getVersion = () => {
    // if(ACPGriffon){
    //   Alert.alert(JSON.stringify(ACPGriffon));
    //      ACPGriffon.getVersion().then((version) => {
    //        Alert.alert(`Version:: ${version}`);
    //        this.setState(() => ({version}));
    //      });
         
    //  }
  };
    
  render() {
    return (
      <ImageBackground source={require('../images/griffon.png')} style={styles.image} imageStyle={{resizeMode: 'contain'}}>
      <Text style={styles.title}>ACP Griffon</Text>
      <View style={styles.container}>
        <Text style={styles.text} onPress={this.startGriffonSession}>Start Session</Text>
        <Text style={styles.text} onPress={this.getVersion}>Get Version</Text>
      </View>
      <View style={styles.infoTextContainer}>
        <Text style={{fontSize: 12, color: "red"}}>Is Griffon Registered: {this.state.isRegistered.toString()}</Text>
        <Text style={{fontSize: 12, color: "red"}}>Griffon version: {this.state.version}</Text>
      </View>
      </ImageBackground>
      
    );
  }
}


const styles = StyleSheet.create({
  container: {
    flexDirection: "column",
    justifyContent:"center",
    alignItems: "center"
  },
  image: {
    flex: 1,
    padding: 24,
    justifyContent: "space-between"
  },
  text: {
    backgroundColor: '#e7e7e7',
    color: '#555555',
    height: 40,
    marginVertical: 10,
    borderColor: "#20232a",
    borderRadius: 5,
    borderWidth: 2,
    aspectRatio: 4,
    fontWeight: "bold",
    fontSize: 16,
    textAlign: "center",
    textAlignVertical: "center"
  },
  title:{
    marginTop: 16,
    paddingVertical: 8,
    borderWidth: 4,
    borderColor: "#20232a",
    backgroundColor: "#61dafb",
    color: "#20232a",
    textAlign: "center",
    fontSize: 30,
    fontWeight: "bold"

  },
  infoTextContainer:{
    flexDirection: "row",
    justifyContent: "space-between"
  }
});
